services:
  alice:
    build: .
    image: mesh/mesh-example-image:latest
    hostname: alice
    ports:
      - "8001:8001"
    volumes:
      - ./example/:/code
    environment:
      - ENV=development
    command: fastapi dev --host 0.0.0.0 --port 8001 --reload app/main.py
    restart: always

  bob:
    image: mesh/mesh-example-image:latest
    hostname: bob
    ports:
      - "8002:8002"
    volumes:
      - ./example/:/code
    environment:
      - ENV=development
      - JOIN_TO=ws://alice:8001/mesh
    command: fastapi dev --host 0.0.0.0 --port 8002 --reload app/main.py
    restart: always
    depends_on:
      - alice

  charlie:
    image: mesh/mesh-example-image:latest
    hostname: charlie
    ports:
      - "8003:8003"
    volumes:
      - ./example/:/code
    environment:
      - ENV=development
    command: fastapi dev --host 0.0.0.0 --port 8003 --reload app/main.py
    restart: always

  dave:
    image: mesh/mesh-example-image:latest
    hostname: dave
    ports:
      - "8004:8004"
    volumes:
      - ./example/:/code
    environment:
      - ENV=development
      - JOIN_TO=ws://charlie:8003/mesh
    command: fastapi dev --host 0.0.0.0 --port 8004 --reload app/main.py
    restart: always
    depends_on:
      - charlie

