site_name: Mesh Documentation
site_url: https://mesh.github.io/

theme:
  name: material
  palette:
    primary: black
    accent: white
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Architecture: 
    - Overview: architecture/overview.md
    - Protocol: architecture/protocol.md
    - Proof: architecture/proof.md
  - User Guide:
    # - Getting Started: user-guide/getting-started.md
    # - Managing Data: user-guide/managing-data.md
    - References: autoapi/
  - About:
    - License: license.md

plugins:
  - search
  - privacy
  - optimize:
      optimize_png: false
      optimize_jpg: false
      exclude:
        - "*.png"       # Ignores a specific directory
  - social
  - mkdocs-autoapi:
      autoapi_add_nav_entry: False
      autoapi_keep_files: False
      autoapi_root: autoapi
      autoapi_file_patterns:
        - "mesh/*.py"  # Automatically grab all Python files
  - mkdocstrings

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-TK7G4XHYFL
  consent:
    title: Cookie consent
    actions:
      - accept
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  copyright: >
    Copyright &copy; 2026 - 2026 Martin Donath –
    <a href="#__consent">Change cookie settings</a>


extra_javascript:
  - assets/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js